// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// [Google Cloud Endpoints](https://cloud.google.com/appengine/docs/python/endpoints/)
/// configuration for API handlers.
public struct ApiConfigHandler: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Action to take when users access resources that require
  /// authentication. Defaults to `redirect`.
  public var authFailAction: AuthFailAction = AuthFailAction()

  /// Level of login required to access this resource. Defaults to
  /// `optional`.
  public var login: LoginRequirement = LoginRequirement()

  /// Path to the script from the application root directory.
  public var script: Swift.String = Swift.String()

  /// Security (HTTPS) enforcement for this URL.
  public var securityLevel: SecurityLevel = SecurityLevel()

  /// URL to serve the endpoint at.
  public var url: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ApiConfigHandler`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApiConfigHandler().with { $0.authFailAction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let authFailAction = CodingKeys(stringValue: "authFailAction")
    static let login = CodingKeys(stringValue: "login")
    static let script = CodingKeys(stringValue: "script")
    static let securityLevel = CodingKeys(stringValue: "securityLevel")
    static let url = CodingKeys(stringValue: "url")

    static let _knownKeys: Set<Swift.String> = [
      "authFailAction",
      "login",
      "script",
      "securityLevel",
      "url",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AuthFailAction.self, forKey: .authFailAction) {
      self.authFailAction = value
    }
    if let value = try container.decodeIfPresent(LoginRequirement.self, forKey: .login) {
      self.login = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .script) {
      self.script = value
    }
    if let value = try container.decodeIfPresent(SecurityLevel.self, forKey: .securityLevel) {
      self.securityLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .url) {
      self.url = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.authFailAction, forKey: .authFailAction)
    try container.encode(self.login, forKey: .login)
    try container.encode(self.script, forKey: .script)
    try container.encode(self.securityLevel, forKey: .securityLevel)
    try container.encode(self.url, forKey: .url)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.ApiConfigHandler"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
