// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages App Engine applications.
///
/// @Snippet(path: "ApplicationsQuickstart")
public final class ApplicationsClient: Clients.ApplicationsProtocol, Sendable {
  let inner: any Clients.ApplicationsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `ApplicationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApplicationsStub = try Clients.ApplicationsTransport(options)
    inner = Clients.ApplicationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApplicationsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Gets information about an application.
  ///
  /// @Snippet(path: "Applications_GetApplication")
  public func getApplication(
    request: GetApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Application {
    try await self.inner.getApplication(request: request, options: options)
  }

  /// Creates an App Engine application for a Google Cloud Platform project.
  /// Required fields:
  ///
  /// * `id` - The ID of the target Cloud Platform project.
  /// * *location* - The [region](https://cloud.google.com/appengine/docs/locations) where you want the App Engine application located.
  ///
  /// For more information about App Engine applications, see [Managing Projects, Applications, and Billing](https://cloud.google.com/appengine/docs/standard/python/console/).
  ///
  /// @Snippet(path: "Applications_CreateApplication")
  public func createApplication(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createApplication(request: request, options: options)
  }

  /// Creates an App Engine application for a Google Cloud Platform project.
  /// Required fields:
  ///
  /// * `id` - The ID of the target Cloud Platform project.
  /// * *location* - The [region](https://cloud.google.com/appengine/docs/locations) where you want the App Engine application located.
  ///
  /// For more information about App Engine applications, see [Managing Projects, Applications, and Billing](https://cloud.google.com/appengine/docs/standard/python/console/).
  ///
  /// @Snippet(path: "Applications_CreateApplication")
  public func createApplicationPollingUntilDone(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Application>.State in
      return try op._extractStatus(Application.self)
    }
    let rawOp = try await self.createApplication(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the specified Application resource.
  /// You can update the following fields:
  ///
  /// * `auth_domain` - Google authentication domain for controlling user access to the application.
  /// * `default_cookie_expiration` - Cookie expiration policy for the application.
  /// * `iap` - Identity-Aware Proxy properties for the application.
  ///
  /// @Snippet(path: "Applications_UpdateApplication")
  public func updateApplication(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateApplication(request: request, options: options)
  }

  /// Updates the specified Application resource.
  /// You can update the following fields:
  ///
  /// * `auth_domain` - Google authentication domain for controlling user access to the application.
  /// * `default_cookie_expiration` - Cookie expiration policy for the application.
  /// * `iap` - Identity-Aware Proxy properties for the application.
  ///
  /// @Snippet(path: "Applications_UpdateApplication")
  public func updateApplicationPollingUntilDone(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Application>.State in
      return try op._extractStatus(Application.self)
    }
    let rawOp = try await self.updateApplication(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Recreates the required App Engine features for the specified App Engine
  /// application, for example a Cloud Storage bucket or App Engine service
  /// account.
  /// Use this method if you receive an error message about a missing feature,
  /// for example, *Error retrieving the App Engine service account*.
  /// If you have deleted your App Engine service account, this will
  /// not be able to recreate it. Instead, you should attempt to use the
  /// IAM undelete API if possible at https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/undelete?apix_params=%7B"name"%3A"projects%2F-%2FserviceAccounts%2Funique_id"%2C"resource"%3A%7B%7D%7D .
  /// If the deletion was recent, the numeric ID can be found in the Cloud
  /// Console Activity Log.
  ///
  /// @Snippet(path: "Applications_RepairApplication")
  public func repairApplication(
    request: RepairApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.repairApplication(request: request, options: options)
  }

  /// Recreates the required App Engine features for the specified App Engine
  /// application, for example a Cloud Storage bucket or App Engine service
  /// account.
  /// Use this method if you receive an error message about a missing feature,
  /// for example, *Error retrieving the App Engine service account*.
  /// If you have deleted your App Engine service account, this will
  /// not be able to recreate it. Instead, you should attempt to use the
  /// IAM undelete API if possible at https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/undelete?apix_params=%7B"name"%3A"projects%2F-%2FserviceAccounts%2Funique_id"%2C"resource"%3A%7B%7D%7D .
  /// If the deletion was recent, the numeric ID can be found in the Cloud
  /// Console Activity Log.
  ///
  /// @Snippet(path: "Applications_RepairApplication")
  public func repairApplicationPollingUntilDone(
    request: RepairApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Application>.State in
      return try op._extractStatus(Application.self)
    }
    let rawOp = try await self.repairApplication(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Applications_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Applications_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApplicationsClient`.
  ///
  /// To mock `ApplicationsClient` change your functions to receive
  /// `some ApplicationsProtocol` or `any ApplicationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApplicationsProtocol: Sendable {
    /// See `ApplicationsClient.getApplication`.
    func getApplication(
      request: GetApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.Application

    /// See `ApplicationsClient.createApplication`.
    func createApplication(
      request: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApplicationsClient.createApplication`.
    func createApplicationPollingUntilDone(
      request: CreateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `ApplicationsClient.updateApplication`.
    func updateApplication(
      request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApplicationsClient.updateApplication`.
    func updateApplicationPollingUntilDone(
      request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `ApplicationsClient.repairApplication`.
    func repairApplication(
      request: RepairApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApplicationsClient.repairApplication`.
    func repairApplicationPollingUntilDone(
      request: RepairApplicationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Application>

    /// See `ApplicationsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.ApplicationsProtocol {
  public func getApplication(request: GetApplicationRequest) async throws
    -> GoogleAppEngineV1.Application
  {
    try await self.getApplication(request: request, options: .init())
  }

  public func getApplication(
    request: GetApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Application {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApplication(
    name: Swift.String,
  ) async throws -> GoogleAppEngineV1.Application {
    let request = GetApplicationRequest().with {
      $0.name = name
    }
    return try await self.getApplication(request: request)
  }

  public func createApplication(request: CreateApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createApplication(request: request, options: .init())
  }

  public func createApplication(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApplicationPollingUntilDone(request: CreateApplicationRequest) async throws
    -> any GoogleGax.PollableOperation<Application>
  {
    try await self.createApplicationPollingUntilDone(request: request, options: .init())
  }

  public func createApplicationPollingUntilDone(
    request: CreateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateApplication(request: UpdateApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateApplication(request: request, options: .init())
  }

  public func updateApplication(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApplicationPollingUntilDone(request: UpdateApplicationRequest) async throws
    -> any GoogleGax.PollableOperation<Application>
  {
    try await self.updateApplicationPollingUntilDone(request: request, options: .init())
  }

  public func updateApplicationPollingUntilDone(
    request: UpdateApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func repairApplication(request: RepairApplicationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.repairApplication(request: request, options: .init())
  }

  public func repairApplication(
    request: RepairApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func repairApplicationPollingUntilDone(request: RepairApplicationRequest) async throws
    -> any GoogleGax.PollableOperation<Application>
  {
    try await self.repairApplicationPollingUntilDone(request: request, options: .init())
  }

  public func repairApplicationPollingUntilDone(
    request: RepairApplicationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Application> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Application>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Applications_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
