// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// App Engine admin service audit log.
public struct AuditData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Detailed information about methods that require it. Does not include
  /// simple Get, List or Delete methods because all significant information
  /// (resource name, number of returned elements for List operations) is already
  /// included in parent audit log message.
  public var method: MethodOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuditData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditData().with { $0.updateService = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let updateService = CodingKeys(stringValue: "updateService")
    static let createVersion = CodingKeys(stringValue: "createVersion")

    static let _knownKeys: Set<Swift.String> = [
      "updateService",
      "createVersion",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var method: MethodOneOf? = nil
    let methodCheckAndSet = {
      if method != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'method'"))
      }
      method = $0
    }
    if let updateService = try container.decodeIfPresent(
      UpdateServiceMethod?.self, forKey: .updateService)
    {
      try methodCheckAndSet(.updateService(updateService))
    }
    if let createVersion = try container.decodeIfPresent(
      CreateVersionMethod?.self, forKey: .createVersion)
    {
      try methodCheckAndSet(.createVersion(createVersion))
    }
    self.method = method
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.method {
      switch choice {
      case .updateService(let value):
        try container.encode(value, forKey: .updateService)
      case .createVersion(let value):
        try container.encode(value, forKey: .createVersion)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Detailed information about methods that require it. Does not include
  /// simple Get, List or Delete methods because all significant information
  /// (resource name, number of returned elements for List operations) is already
  /// included in parent audit log message.
  public enum MethodOneOf: Codable, Equatable, Sendable {
    /// Detailed information about UpdateService call.
    indirect case updateService(UpdateServiceMethod?)
    /// Detailed information about CreateVersion call.
    indirect case createVersion(CreateVersionMethod?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.AuditData"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
