// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Automatic scaling is based on request rate, response latencies, and other
/// application metrics.
public struct AutomaticScaling: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time period that the
  /// [Autoscaler](https://cloud.google.com/compute/docs/autoscaler/)
  /// should wait before it starts collecting information from a new instance.
  /// This prevents the autoscaler from collecting information when the instance
  /// is initializing, during which the collected usage would not be reliable.
  /// Only applicable in the App Engine flexible environment.
  public var coolDownPeriod: GoogleWKT.WKTDuration? = nil

  /// Target scaling by CPU usage.
  public var cpuUtilization: CpuUtilization? = nil

  /// Number of concurrent requests an automatic scaling instance can accept
  /// before the scheduler spawns a new instance.
  ///
  /// Defaults to a runtime-specific value.
  public var maxConcurrentRequests: Swift.Int32 = Swift.Int32()

  /// Maximum number of idle instances that should be maintained for this
  /// version.
  public var maxIdleInstances: Swift.Int32 = Swift.Int32()

  /// Maximum number of instances that should be started to handle requests for
  /// this version.
  public var maxTotalInstances: Swift.Int32 = Swift.Int32()

  /// Maximum amount of time that a request should wait in the pending queue
  /// before starting a new instance to handle it.
  public var maxPendingLatency: GoogleWKT.WKTDuration? = nil

  /// Minimum number of idle instances that should be maintained for
  /// this version. Only applicable for the default version of a service.
  public var minIdleInstances: Swift.Int32 = Swift.Int32()

  /// Minimum number of running instances that should be maintained for this
  /// version.
  public var minTotalInstances: Swift.Int32 = Swift.Int32()

  /// Minimum amount of time a request should wait in the pending queue before
  /// starting a new instance to handle it.
  public var minPendingLatency: GoogleWKT.WKTDuration? = nil

  /// Target scaling by request utilization.
  public var requestUtilization: RequestUtilization? = nil

  /// Target scaling by disk usage.
  public var diskUtilization: DiskUtilization? = nil

  /// Target scaling by network usage.
  public var networkUtilization: NetworkUtilization? = nil

  /// Scheduler settings for standard environment.
  public var standardSchedulerSettings: StandardSchedulerSettings? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AutomaticScaling`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomaticScaling().with { $0.coolDownPeriod = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let coolDownPeriod = CodingKeys(stringValue: "coolDownPeriod")
    static let cpuUtilization = CodingKeys(stringValue: "cpuUtilization")
    static let maxConcurrentRequests = CodingKeys(stringValue: "maxConcurrentRequests")
    static let maxIdleInstances = CodingKeys(stringValue: "maxIdleInstances")
    static let maxTotalInstances = CodingKeys(stringValue: "maxTotalInstances")
    static let maxPendingLatency = CodingKeys(stringValue: "maxPendingLatency")
    static let minIdleInstances = CodingKeys(stringValue: "minIdleInstances")
    static let minTotalInstances = CodingKeys(stringValue: "minTotalInstances")
    static let minPendingLatency = CodingKeys(stringValue: "minPendingLatency")
    static let requestUtilization = CodingKeys(stringValue: "requestUtilization")
    static let diskUtilization = CodingKeys(stringValue: "diskUtilization")
    static let networkUtilization = CodingKeys(stringValue: "networkUtilization")
    static let standardSchedulerSettings = CodingKeys(stringValue: "standardSchedulerSettings")

    static let _knownKeys: Set<Swift.String> = [
      "coolDownPeriod",
      "cpuUtilization",
      "maxConcurrentRequests",
      "maxIdleInstances",
      "maxTotalInstances",
      "maxPendingLatency",
      "minIdleInstances",
      "minTotalInstances",
      "minPendingLatency",
      "requestUtilization",
      "diskUtilization",
      "networkUtilization",
      "standardSchedulerSettings",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.coolDownPeriod = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .coolDownPeriod)
    self.cpuUtilization = try container.decodeIfPresent(
      CpuUtilization.self, forKey: .cpuUtilization)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxConcurrentRequests) {
      self.maxConcurrentRequests = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxIdleInstances) {
      self.maxIdleInstances = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxTotalInstances) {
      self.maxTotalInstances = value
    }
    self.maxPendingLatency = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .maxPendingLatency)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minIdleInstances) {
      self.minIdleInstances = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minTotalInstances) {
      self.minTotalInstances = value
    }
    self.minPendingLatency = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .minPendingLatency)
    self.requestUtilization = try container.decodeIfPresent(
      RequestUtilization.self, forKey: .requestUtilization)
    self.diskUtilization = try container.decodeIfPresent(
      DiskUtilization.self, forKey: .diskUtilization)
    self.networkUtilization = try container.decodeIfPresent(
      NetworkUtilization.self, forKey: .networkUtilization)
    self.standardSchedulerSettings = try container.decodeIfPresent(
      StandardSchedulerSettings.self, forKey: .standardSchedulerSettings)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.coolDownPeriod, forKey: .coolDownPeriod)
    try container.encodeIfPresent(self.cpuUtilization, forKey: .cpuUtilization)
    try container.encode(self.maxConcurrentRequests, forKey: .maxConcurrentRequests)
    try container.encode(self.maxIdleInstances, forKey: .maxIdleInstances)
    try container.encode(self.maxTotalInstances, forKey: .maxTotalInstances)
    try container.encodeIfPresent(self.maxPendingLatency, forKey: .maxPendingLatency)
    try container.encode(self.minIdleInstances, forKey: .minIdleInstances)
    try container.encode(self.minTotalInstances, forKey: .minTotalInstances)
    try container.encodeIfPresent(self.minPendingLatency, forKey: .minPendingLatency)
    try container.encodeIfPresent(self.requestUtilization, forKey: .requestUtilization)
    try container.encodeIfPresent(self.diskUtilization, forKey: .diskUtilization)
    try container.encodeIfPresent(self.networkUtilization, forKey: .networkUtilization)
    try container.encodeIfPresent(
      self.standardSchedulerSettings, forKey: .standardSchedulerSettings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.AutomaticScaling"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
