// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An SSL certificate obtained from a certificate authority.
public struct CertificateRawData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// PEM encoded x.509 public key certificate. This field is set once on
  /// certificate creation. Must include the header and footer. Example:
  /// <pre>
  /// -----BEGIN CERTIFICATE-----
  /// <certificate_value>
  /// -----END CERTIFICATE-----
  /// </pre>
  public var publicCertificate: Swift.String = Swift.String()

  /// Unencrypted PEM encoded RSA private key. This field is set once on
  /// certificate creation and then encrypted. The key size must be 2048
  /// bits or fewer. Must include the header and footer. Example:
  /// <pre>
  /// -----BEGIN RSA PRIVATE KEY-----
  /// <unencrypted_key_value>
  /// -----END RSA PRIVATE KEY-----
  /// </pre>
  /// @InputOnly
  public var privateKey: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateRawData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateRawData().with { $0.publicCertificate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let publicCertificate = CodingKeys(stringValue: "publicCertificate")
    static let privateKey = CodingKeys(stringValue: "privateKey")

    static let _knownKeys: Set<Swift.String> = [
      "publicCertificate",
      "privateKey",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publicCertificate) {
      self.publicCertificate = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .privateKey) {
      self.privateKey = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.publicCertificate, forKey: .publicCertificate)
    try container.encode(self.privateKey, forKey: .privateKey)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.CertificateRawData"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
