// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// [Cloud Endpoints](https://cloud.google.com/endpoints) configuration.
/// The Endpoints API Service provides tooling for serving Open API and gRPC
/// endpoints via an NGINX proxy. Only valid for App Engine Flexible environment
/// deployments.
///
/// The fields here refer to the name and configuration ID of a "service"
/// resource in the [Service Management API](https://cloud.google.com/service-management/overview).
public struct EndpointsApiService: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Endpoints service name which is the name of the "service" resource in the
  /// Service Management API. For example "myapi.endpoints.myproject.cloud.goog"
  public var name: Swift.String = Swift.String()

  /// Endpoints service configuration ID as specified by the Service Management
  /// API. For example "2016-09-19r1".
  ///
  /// By default, the rollout strategy for Endpoints is `RolloutStrategy.FIXED`.
  /// This means that Endpoints starts up with a particular configuration ID.
  /// When a new configuration is rolled out, Endpoints must be given the new
  /// configuration ID. The `config_id` field is used to give the configuration
  /// ID and is required in this case.
  ///
  /// Endpoints also has a rollout strategy called `RolloutStrategy.MANAGED`.
  /// When using this, Endpoints fetches the latest configuration and does not
  /// need the configuration ID. In this case, `config_id` must be omitted.
  public var configId: Swift.String = Swift.String()

  /// Endpoints rollout strategy. If `FIXED`, `config_id` must be specified. If
  /// `MANAGED`, `config_id` must be omitted.
  public var rolloutStrategy: EndpointsApiService.RolloutStrategy =
    EndpointsApiService.RolloutStrategy()

  /// Enable or disable trace sampling. By default, this is set to false for
  /// enabled.
  public var disableTraceSampling: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EndpointsApiService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EndpointsApiService().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let configId = CodingKeys(stringValue: "configId")
    static let rolloutStrategy = CodingKeys(stringValue: "rolloutStrategy")
    static let disableTraceSampling = CodingKeys(stringValue: "disableTraceSampling")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "configId",
      "rolloutStrategy",
      "disableTraceSampling",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .configId) {
      self.configId = value
    }
    if let value = try container.decodeIfPresent(
      EndpointsApiService.RolloutStrategy.self, forKey: .rolloutStrategy)
    {
      self.rolloutStrategy = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableTraceSampling) {
      self.disableTraceSampling = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.configId, forKey: .configId)
    try container.encode(self.rolloutStrategy, forKey: .rolloutStrategy)
    try container.encode(self.disableTraceSampling, forKey: .disableTraceSampling)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Available rollout strategies.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum RolloutStrategy: Codable, Equatable, Hashable, Sendable {
    /// Not specified. Defaults to `FIXED`.
    case unspecifiedRolloutStrategy
    /// Endpoints service configuration ID will be fixed to the configuration ID
    /// specified by `config_id`.
    case fixed
    /// Endpoints service configuration ID will be updated with each rollout.
    case managed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecifiedRolloutStrategy
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecifiedRolloutStrategy: return 0
      case .fixed: return 1
      case .managed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecifiedRolloutStrategy: return "UNSPECIFIED_ROLLOUT_STRATEGY"
      case .fixed: return "FIXED"
      case .managed: return "MANAGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolloutStrategy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED_ROLLOUT_STRATEGY": self = .unspecifiedRolloutStrategy
      case "FIXED": self = .fixed
      case "MANAGED": self = .managed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolloutStrategy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecifiedRolloutStrategy
      case 1: self = .fixed
      case 2: self = .managed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecifiedRolloutStrategy: return try container.encode("UNSPECIFIED_ROLLOUT_STRATEGY")
      case .fixed: return try container.encode("FIXED")
      case .managed: return try container.encode("MANAGED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.EndpointsApiService"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
