// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Custom static error page to be served when an error occurs.
public struct ErrorHandler: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Error condition this handler applies to.
  public var errorCode: ErrorHandler.ErrorCode = ErrorHandler.ErrorCode()

  /// Static file content to be served for this error.
  public var staticFile: Swift.String = Swift.String()

  /// MIME type of file. Defaults to `text/html`.
  public var mimeType: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ErrorHandler`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ErrorHandler().with { $0.errorCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let errorCode = CodingKeys(stringValue: "errorCode")
    static let staticFile = CodingKeys(stringValue: "staticFile")
    static let mimeType = CodingKeys(stringValue: "mimeType")

    static let _knownKeys: Set<Swift.String> = [
      "errorCode",
      "staticFile",
      "mimeType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ErrorHandler.ErrorCode.self, forKey: .errorCode) {
      self.errorCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .staticFile) {
      self.staticFile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.staticFile, forKey: .staticFile)
    try container.encode(self.mimeType, forKey: .mimeType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Error codes.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ErrorCode: Codable, Equatable, Hashable, Sendable {
    /// All other error types.
    case `default`
    /// Application has exceeded a resource quota.
    case overQuota
    /// Client blocked by the application's Denial of Service protection
    /// configuration.
    case dosApiDenial
    /// Deadline reached before the application responds.
    case timeout
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .`default`
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .`default`: return 0
      case .overQuota: return 1
      case .dosApiDenial: return 2
      case .timeout: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .`default`: return "ERROR_CODE_DEFAULT"
      case .overQuota: return "ERROR_CODE_OVER_QUOTA"
      case .dosApiDenial: return "ERROR_CODE_DOS_API_DENIAL"
      case .timeout: return "ERROR_CODE_TIMEOUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ErrorCode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ERROR_CODE_UNSPECIFIED": self = .`default`
      case "ERROR_CODE_DEFAULT": self = .`default`
      case "ERROR_CODE_OVER_QUOTA": self = .overQuota
      case "ERROR_CODE_DOS_API_DENIAL": self = .dosApiDenial
      case "ERROR_CODE_TIMEOUT": self = .timeout
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ErrorCode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .`default`
      case 1: self = .overQuota
      case 2: self = .dosApiDenial
      case 3: self = .timeout
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`default`: return try container.encode("ERROR_CODE_DEFAULT")
      case .overQuota: return try container.encode("ERROR_CODE_OVER_QUOTA")
      case .dosApiDenial: return try container.encode("ERROR_CODE_DOS_API_DENIAL")
      case .timeout: return try container.encode("ERROR_CODE_TIMEOUT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.ErrorHandler"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
