// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class FirewallRetry: FirewallStub {
    let inner: any FirewallStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any FirewallStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listIngressRules(
      request: ListIngressRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListIngressRulesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListIngressRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleAppEngineV1.ListIngressRulesResponse
          in
          return try await self.inner.listIngressRules(request: r, options: o)
        })
    }

    public func batchUpdateIngressRules(
      request: BatchUpdateIngressRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.BatchUpdateIngressRulesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchUpdateIngressRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleAppEngineV1.BatchUpdateIngressRulesResponse
          in
          return try await self.inner.batchUpdateIngressRules(request: r, options: o)
        })
    }

    public func createIngressRule(
      request: CreateIngressRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateIngressRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.createIngressRule(request: r, options: o)
        })
    }

    public func getIngressRule(
      request: GetIngressRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetIngressRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.getIngressRule(request: r, options: o)
        })
    }

    public func updateIngressRule(
      request: UpdateIngressRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateIngressRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.updateIngressRule(request: r, options: o)
        })
    }

    public func deleteIngressRule(
      request: DeleteIngressRuleRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteIngressRuleRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteIngressRule(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
