// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Health checking configuration for VM instances. Unhealthy instances
/// are killed and replaced with new instances. Only applicable for
/// instances in App Engine flexible environment.
public struct HealthCheck: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether to explicitly disable health checks for this instance.
  public var disableHealthCheck: Swift.Bool = Swift.Bool()

  /// Host header to send when performing an HTTP health check.
  /// Example: "myapp.appspot.com"
  public var host: Swift.String = Swift.String()

  /// Number of consecutive successful health checks required before receiving
  /// traffic.
  public var healthyThreshold: Swift.UInt32 = Swift.UInt32()

  /// Number of consecutive failed health checks required before removing
  /// traffic.
  public var unhealthyThreshold: Swift.UInt32 = Swift.UInt32()

  /// Number of consecutive failed health checks required before an instance is
  /// restarted.
  public var restartThreshold: Swift.UInt32 = Swift.UInt32()

  /// Interval between health checks.
  public var checkInterval: GoogleWKT.WKTDuration? = nil

  /// Time before the health check is considered failed.
  public var timeout: GoogleWKT.WKTDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HealthCheck`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HealthCheck().with { $0.disableHealthCheck = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let disableHealthCheck = CodingKeys(stringValue: "disableHealthCheck")
    static let host = CodingKeys(stringValue: "host")
    static let healthyThreshold = CodingKeys(stringValue: "healthyThreshold")
    static let unhealthyThreshold = CodingKeys(stringValue: "unhealthyThreshold")
    static let restartThreshold = CodingKeys(stringValue: "restartThreshold")
    static let checkInterval = CodingKeys(stringValue: "checkInterval")
    static let timeout = CodingKeys(stringValue: "timeout")

    static let _knownKeys: Set<Swift.String> = [
      "disableHealthCheck",
      "host",
      "healthyThreshold",
      "unhealthyThreshold",
      "restartThreshold",
      "checkInterval",
      "timeout",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disableHealthCheck) {
      self.disableHealthCheck = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
      self.host = value
    }
    if let value = try container.decodeIfPresent(Swift.UInt32.self, forKey: .healthyThreshold) {
      self.healthyThreshold = value
    }
    if let value = try container.decodeIfPresent(Swift.UInt32.self, forKey: .unhealthyThreshold) {
      self.unhealthyThreshold = value
    }
    if let value = try container.decodeIfPresent(Swift.UInt32.self, forKey: .restartThreshold) {
      self.restartThreshold = value
    }
    self.checkInterval = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .checkInterval)
    self.timeout = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .timeout)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.disableHealthCheck, forKey: .disableHealthCheck)
    try container.encode(self.host, forKey: .host)
    try container.encode(self.healthyThreshold, forKey: .healthyThreshold)
    try container.encode(self.unhealthyThreshold, forKey: .unhealthyThreshold)
    try container.encode(self.restartThreshold, forKey: .restartThreshold)
    try container.encodeIfPresent(self.checkInterval, forKey: .checkInterval)
    try container.encodeIfPresent(self.timeout, forKey: .timeout)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.HealthCheck"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
