// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Available inbound services.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum InboundServiceType: Codable, Equatable, Hashable, Sendable {
  /// Not specified.
  case inboundServiceUnspecified
  /// Allows an application to receive mail.
  case inboundServiceMail
  /// Allows an application to receive email-bound notifications.
  case inboundServiceMailBounce
  /// Allows an application to receive error stanzas.
  case inboundServiceXmppError
  /// Allows an application to receive instant messages.
  case inboundServiceXmppMessage
  /// Allows an application to receive user subscription POSTs.
  case inboundServiceXmppSubscribe
  /// Allows an application to receive a user's chat presence.
  case inboundServiceXmppPresence
  /// Registers an application for notifications when a client connects or
  /// disconnects from a channel.
  case inboundServiceChannelPresence
  /// Enables warmup requests.
  case inboundServiceWarmup
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .inboundServiceUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .inboundServiceUnspecified: return 0
    case .inboundServiceMail: return 1
    case .inboundServiceMailBounce: return 2
    case .inboundServiceXmppError: return 3
    case .inboundServiceXmppMessage: return 4
    case .inboundServiceXmppSubscribe: return 5
    case .inboundServiceXmppPresence: return 6
    case .inboundServiceChannelPresence: return 7
    case .inboundServiceWarmup: return 9
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .inboundServiceUnspecified: return "INBOUND_SERVICE_UNSPECIFIED"
    case .inboundServiceMail: return "INBOUND_SERVICE_MAIL"
    case .inboundServiceMailBounce: return "INBOUND_SERVICE_MAIL_BOUNCE"
    case .inboundServiceXmppError: return "INBOUND_SERVICE_XMPP_ERROR"
    case .inboundServiceXmppMessage: return "INBOUND_SERVICE_XMPP_MESSAGE"
    case .inboundServiceXmppSubscribe: return "INBOUND_SERVICE_XMPP_SUBSCRIBE"
    case .inboundServiceXmppPresence: return "INBOUND_SERVICE_XMPP_PRESENCE"
    case .inboundServiceChannelPresence: return "INBOUND_SERVICE_CHANNEL_PRESENCE"
    case .inboundServiceWarmup: return "INBOUND_SERVICE_WARMUP"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InboundServiceType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "INBOUND_SERVICE_UNSPECIFIED": self = .inboundServiceUnspecified
    case "INBOUND_SERVICE_MAIL": self = .inboundServiceMail
    case "INBOUND_SERVICE_MAIL_BOUNCE": self = .inboundServiceMailBounce
    case "INBOUND_SERVICE_XMPP_ERROR": self = .inboundServiceXmppError
    case "INBOUND_SERVICE_XMPP_MESSAGE": self = .inboundServiceXmppMessage
    case "INBOUND_SERVICE_XMPP_SUBSCRIBE": self = .inboundServiceXmppSubscribe
    case "INBOUND_SERVICE_XMPP_PRESENCE": self = .inboundServiceXmppPresence
    case "INBOUND_SERVICE_CHANNEL_PRESENCE": self = .inboundServiceChannelPresence
    case "INBOUND_SERVICE_WARMUP": self = .inboundServiceWarmup
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InboundServiceType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .inboundServiceUnspecified
    case 1: self = .inboundServiceMail
    case 2: self = .inboundServiceMailBounce
    case 3: self = .inboundServiceXmppError
    case 4: self = .inboundServiceXmppMessage
    case 5: self = .inboundServiceXmppSubscribe
    case 6: self = .inboundServiceXmppPresence
    case 7: self = .inboundServiceChannelPresence
    case 9: self = .inboundServiceWarmup
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .inboundServiceUnspecified: return try container.encode("INBOUND_SERVICE_UNSPECIFIED")
    case .inboundServiceMail: return try container.encode("INBOUND_SERVICE_MAIL")
    case .inboundServiceMailBounce: return try container.encode("INBOUND_SERVICE_MAIL_BOUNCE")
    case .inboundServiceXmppError: return try container.encode("INBOUND_SERVICE_XMPP_ERROR")
    case .inboundServiceXmppMessage: return try container.encode("INBOUND_SERVICE_XMPP_MESSAGE")
    case .inboundServiceXmppSubscribe: return try container.encode("INBOUND_SERVICE_XMPP_SUBSCRIBE")
    case .inboundServiceXmppPresence: return try container.encode("INBOUND_SERVICE_XMPP_PRESENCE")
    case .inboundServiceChannelPresence:
      return try container.encode("INBOUND_SERVICE_CHANNEL_PRESENCE")
    case .inboundServiceWarmup: return try container.encode("INBOUND_SERVICE_WARMUP")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
