// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages instances of a version.
///
/// @Snippet(path: "InstancesQuickstart")
public final class InstancesClient: Clients.InstancesProtocol, Sendable {
  let inner: any Clients.InstancesStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `InstancesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.InstancesStub = try Clients.InstancesTransport(options)
    inner = Clients.InstancesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.InstancesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists the instances of a version.
  ///
  /// Tip: To aggregate details about instances over time, see the
  /// [Stackdriver Monitoring API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list).
  ///
  /// @Snippet(path: "Instances_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets instance information.
  ///
  /// @Snippet(path: "Instances_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Stops a running instance.
  ///
  /// The instance might be automatically recreated based on the scaling settings
  /// of the version. For more information, see "How Instances are Managed"
  /// ([standard environment](https://cloud.google.com/appengine/docs/standard/python/how-instances-are-managed) |
  /// [flexible environment](https://cloud.google.com/appengine/docs/flexible/python/how-instances-are-managed)).
  ///
  /// To ensure that instances are not re-created and avoid getting billed, you
  /// can stop all instances within the target version by changing the serving
  /// status of the version to `STOPPED` with the
  /// [`apps.services.versions.patch`](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions/patch)
  /// method.
  ///
  /// @Snippet(path: "Instances_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Stops a running instance.
  ///
  /// The instance might be automatically recreated based on the scaling settings
  /// of the version. For more information, see "How Instances are Managed"
  /// ([standard environment](https://cloud.google.com/appengine/docs/standard/python/how-instances-are-managed) |
  /// [flexible environment](https://cloud.google.com/appengine/docs/flexible/python/how-instances-are-managed)).
  ///
  /// To ensure that instances are not re-created and avoid getting billed, you
  /// can stop all instances within the target version by changing the serving
  /// status of the version to `STOPPED` with the
  /// [`apps.services.versions.patch`](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions/patch)
  /// method.
  ///
  /// @Snippet(path: "Instances_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Enables debugging on a VM instance. This allows you to use the SSH
  /// command to connect to the virtual machine where the instance lives.
  /// While in "debug mode", the instance continues to serve live traffic.
  /// You should delete the instance when you are done debugging and then
  /// allow the system to take over and determine if another instance
  /// should be started.
  ///
  /// Only applicable for instances in App Engine flexible environment.
  ///
  /// @Snippet(path: "Instances_DebugInstance")
  public func debugInstance(
    request: DebugInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.debugInstance(request: request, options: options)
  }

  /// Enables debugging on a VM instance. This allows you to use the SSH
  /// command to connect to the virtual machine where the instance lives.
  /// While in "debug mode", the instance continues to serve live traffic.
  /// You should delete the instance when you are done debugging and then
  /// allow the system to take over and determine if another instance
  /// should be started.
  ///
  /// Only applicable for instances in App Engine flexible environment.
  ///
  /// @Snippet(path: "Instances_DebugInstance")
  public func debugInstancePollingUntilDone(
    request: DebugInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.debugInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Instances_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Instances_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `InstancesClient`.
  ///
  /// To mock `InstancesClient` change your functions to receive
  /// `some InstancesProtocol` or `any InstancesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol InstancesProtocol: Sendable {
    /// See `InstancesClient.deleteInstance`.
    func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `InstancesClient.debugInstance`.
    func debugInstancePollingUntilDone(request: DebugInstanceRequest) async throws -> any GoogleGax
      .PollableOperation<Instance>

    /// See `InstancesClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListInstancesResponse

    /// See `InstancesClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.Instance

    /// See `InstancesClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InstancesClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `InstancesClient.debugInstance`.
    func debugInstance(
      request: DebugInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InstancesClient.debugInstance`.
    func debugInstancePollingUntilDone(
      request: DebugInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `InstancesClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.InstancesProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleAppEngineV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists the instances of a version.
  ///
  /// Tip: To aggregate details about instances over time, see the
  /// [Stackdriver Monitoring API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list).
  ///
  /// @Snippet(path: "Instances_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleAppEngineV1.ListInstancesResponse in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getInstance(request: GetInstanceRequest) async throws -> GoogleAppEngineV1.Instance {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func debugInstance(request: DebugInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.debugInstance(request: request, options: .init())
  }

  public func debugInstance(
    request: DebugInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func debugInstancePollingUntilDone(request: DebugInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.debugInstancePollingUntilDone(request: request, options: .init())
  }

  public func debugInstancePollingUntilDone(
    request: DebugInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Instances_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
