// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An Instance resource is the computing unit that App Engine uses to
/// automatically scale an application.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Full path to the Instance resource in the API.
  /// Example: `apps/myapp/services/default/versions/v1/instances/instance-1`.
  public var name: Swift.String = Swift.String()

  /// Output only. Relative name of the instance within the version.
  /// Example: `instance-1`.
  public var id: Swift.String = Swift.String()

  /// Output only. App Engine release this instance is running on.
  public var appEngineRelease: Swift.String = Swift.String()

  /// Output only. Availability of the instance.
  public var availability: Instance.Availability = Instance.Availability()

  /// Output only. Name of the virtual machine where this instance lives. Only applicable
  /// for instances in App Engine flexible environment.
  public var vmName: Swift.String = Swift.String()

  /// Output only. Zone where the virtual machine is located. Only applicable for instances
  /// in App Engine flexible environment.
  public var vmZoneName: Swift.String = Swift.String()

  /// Output only. Virtual machine ID of this instance. Only applicable for instances in
  /// App Engine flexible environment.
  public var vmId: Swift.String = Swift.String()

  /// Output only. Time that this instance was started.
  ///
  /// @OutputOnly
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Number of requests since this instance was started.
  public var requests: Swift.Int32 = Swift.Int32()

  /// Output only. Number of errors since this instance was started.
  public var errors: Swift.Int32 = Swift.Int32()

  /// Output only. Average queries per second (QPS) over the last minute.
  public var qps: Swift.Float = Swift.Float()

  /// Output only. Average latency (ms) over the last minute.
  public var averageLatency: Swift.Int32 = Swift.Int32()

  /// Output only. Total memory in use (bytes).
  public var memoryUsage: Swift.Int64 = Swift.Int64()

  /// Output only. Status of the virtual machine where this instance lives. Only applicable
  /// for instances in App Engine flexible environment.
  public var vmStatus: Swift.String = Swift.String()

  /// Output only. Whether this instance is in debug mode. Only applicable for instances in
  /// App Engine flexible environment.
  public var vmDebugEnabled: Swift.Bool = Swift.Bool()

  /// Output only. The IP address of this instance. Only applicable for instances in App
  /// Engine flexible environment.
  public var vmIp: Swift.String = Swift.String()

  /// Output only. The liveness health check of this instance. Only applicable for instances
  /// in App Engine flexible environment.
  public var vmLiveness: Instance.Liveness.LivenessState = Instance.Liveness.LivenessState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let id = CodingKeys(stringValue: "id")
    static let appEngineRelease = CodingKeys(stringValue: "appEngineRelease")
    static let availability = CodingKeys(stringValue: "availability")
    static let vmName = CodingKeys(stringValue: "vmName")
    static let vmZoneName = CodingKeys(stringValue: "vmZoneName")
    static let vmId = CodingKeys(stringValue: "vmId")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let requests = CodingKeys(stringValue: "requests")
    static let errors = CodingKeys(stringValue: "errors")
    static let qps = CodingKeys(stringValue: "qps")
    static let averageLatency = CodingKeys(stringValue: "averageLatency")
    static let memoryUsage = CodingKeys(stringValue: "memoryUsage")
    static let vmStatus = CodingKeys(stringValue: "vmStatus")
    static let vmDebugEnabled = CodingKeys(stringValue: "vmDebugEnabled")
    static let vmIp = CodingKeys(stringValue: "vmIp")
    static let vmLiveness = CodingKeys(stringValue: "vmLiveness")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "id",
      "appEngineRelease",
      "availability",
      "vmName",
      "vmZoneName",
      "vmId",
      "startTime",
      "requests",
      "errors",
      "qps",
      "averageLatency",
      "memoryUsage",
      "vmStatus",
      "vmDebugEnabled",
      "vmIp",
      "vmLiveness",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .appEngineRelease) {
      self.appEngineRelease = value
    }
    if let value = try container.decodeIfPresent(Instance.Availability.self, forKey: .availability)
    {
      self.availability = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmName) {
      self.vmName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmZoneName) {
      self.vmZoneName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmId) {
      self.vmId = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .requests) {
      self.requests = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .errors) {
      self.errors = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .qps) {
      self.qps = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .averageLatency) {
      self.averageLatency = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .memoryUsage) {
      self.memoryUsage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmStatus) {
      self.vmStatus = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .vmDebugEnabled) {
      self.vmDebugEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vmIp) {
      self.vmIp = value
    }
    if let value = try container.decodeIfPresent(
      Instance.Liveness.LivenessState.self, forKey: .vmLiveness)
    {
      self.vmLiveness = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.appEngineRelease, forKey: .appEngineRelease)
    try container.encode(self.availability, forKey: .availability)
    try container.encode(self.vmName, forKey: .vmName)
    try container.encode(self.vmZoneName, forKey: .vmZoneName)
    try container.encode(self.vmId, forKey: .vmId)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encode(self.requests, forKey: .requests)
    try container.encode(self.errors, forKey: .errors)
    try container.encode(self.qps, forKey: .qps)
    try container.encode(self.averageLatency, forKey: .averageLatency)
    try container.encode(self.memoryUsage, forKey: .memoryUsage)
    try container.encode(self.vmStatus, forKey: .vmStatus)
    try container.encode(self.vmDebugEnabled, forKey: .vmDebugEnabled)
    try container.encode(self.vmIp, forKey: .vmIp)
    try container.encode(self.vmLiveness, forKey: .vmLiveness)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Wrapper for LivenessState enum.
  public struct Liveness: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Liveness`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Liveness().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Liveness health check status for Flex instances.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum LivenessState: Codable, Equatable, Sendable {
      /// There is no liveness health check for the instance. Only applicable for
      /// instances in App Engine standard environment.
      case unspecified
      /// The health checking system is aware of the instance but its health is
      /// not known at the moment.
      case unknown
      /// The instance is reachable i.e. a connection to the application health
      /// checking endpoint can be established, and conforms to the requirements
      /// defined by the health check.
      case healthy
      /// The instance is reachable, but does not conform to the requirements
      /// defined by the health check.
      case unhealthy
      /// The instance is being drained. The existing connections to the instance
      /// have time to complete, but the new ones are being refused.
      case draining
      /// The instance is unreachable i.e. a connection to the application health
      /// checking endpoint cannot be established, or the server does not respond
      /// within the specified timeout.
      case timeout
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .unknown: return 1
        case .healthy: return 2
        case .unhealthy: return 3
        case .draining: return 4
        case .timeout: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "LIVENESS_STATE_UNSPECIFIED"
        case .unknown: return "UNKNOWN"
        case .healthy: return "HEALTHY"
        case .unhealthy: return "UNHEALTHY"
        case .draining: return "DRAINING"
        case .timeout: return "TIMEOUT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LivenessState/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "LIVENESS_STATE_UNSPECIFIED": self = .unspecified
        case "UNKNOWN": self = .unknown
        case "HEALTHY": self = .healthy
        case "UNHEALTHY": self = .unhealthy
        case "DRAINING": self = .draining
        case "TIMEOUT": self = .timeout
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LivenessState/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .unknown
        case 2: self = .healthy
        case 3: self = .unhealthy
        case 4: self = .draining
        case 5: self = .timeout
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("LIVENESS_STATE_UNSPECIFIED")
        case .unknown: return try container.encode("UNKNOWN")
        case .healthy: return try container.encode("HEALTHY")
        case .unhealthy: return try container.encode("UNHEALTHY")
        case .draining: return try container.encode("DRAINING")
        case .timeout: return try container.encode("TIMEOUT")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.appengine.v1.Instance.Liveness"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Availability of the instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Availability: Codable, Equatable, Sendable {
    case unspecified
    case resident
    case `dynamic`
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resident: return 1
      case .`dynamic`: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .resident: return "RESIDENT"
      case .`dynamic`: return "DYNAMIC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Availability/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "RESIDENT": self = .resident
      case "DYNAMIC": self = .`dynamic`
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Availability/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resident
      case 2: self = .`dynamic`
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("UNSPECIFIED")
      case .resident: return try container.encode("RESIDENT")
      case .`dynamic`: return try container.encode("DYNAMIC")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
