// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Methods to restrict access to a URL based on login status.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum LoginRequirement: Codable, Equatable, Hashable, Sendable {
  /// Not specified. `LOGIN_OPTIONAL` is assumed.
  case loginUnspecified
  /// Does not require that the user is signed in.
  case loginOptional
  /// If the user is not signed in, the `auth_fail_action` is taken.
  /// In addition, if the user is not an administrator for the
  /// application, they are given an error message regardless of
  /// `auth_fail_action`. If the user is an administrator, the handler
  /// proceeds.
  case loginAdmin
  /// If the user has signed in, the handler proceeds normally. Otherwise, the
  /// auth_fail_action is taken.
  case loginRequired
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .loginUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .loginUnspecified: return 0
    case .loginOptional: return 1
    case .loginAdmin: return 2
    case .loginRequired: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .loginUnspecified: return "LOGIN_UNSPECIFIED"
    case .loginOptional: return "LOGIN_OPTIONAL"
    case .loginAdmin: return "LOGIN_ADMIN"
    case .loginRequired: return "LOGIN_REQUIRED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LoginRequirement/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "LOGIN_UNSPECIFIED": self = .loginUnspecified
    case "LOGIN_OPTIONAL": self = .loginOptional
    case "LOGIN_ADMIN": self = .loginAdmin
    case "LOGIN_REQUIRED": self = .loginRequired
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LoginRequirement/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .loginUnspecified
    case 1: self = .loginOptional
    case 2: self = .loginAdmin
    case 3: self = .loginRequired
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .loginUnspecified: return try container.encode("LOGIN_UNSPECIFIED")
    case .loginOptional: return try container.encode("LOGIN_OPTIONAL")
    case .loginAdmin: return try container.encode("LOGIN_ADMIN")
    case .loginRequired: return try container.encode("LOGIN_REQUIRED")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
