// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// State of certificate management. Refers to the most recent certificate
/// acquisition or renewal attempt.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum ManagementStatus: Codable, Equatable, Hashable, Sendable {
  case unspecified
  /// Certificate was successfully obtained and inserted into the serving
  /// system.
  case ok
  /// Certificate is under active attempts to acquire or renew.
  case pending
  /// Most recent renewal failed due to an invalid DNS setup and will be
  /// retried. Renewal attempts will continue to fail until the certificate
  /// domain's DNS configuration is fixed. The last successfully provisioned
  /// certificate may still be serving.
  case failedRetryingNotVisible
  /// All renewal attempts have been exhausted, likely due to an invalid DNS
  /// setup.
  case failedPermanent
  /// Most recent renewal failed due to an explicit CAA record that does not
  /// include one of the in-use CAs (Google CA and Let's Encrypt). Renewals will
  /// continue to fail until the CAA is reconfigured. The last successfully
  /// provisioned certificate may still be serving.
  case failedRetryingCaaForbidden
  /// Most recent renewal failed due to a CAA retrieval failure. This means that
  /// the domain's DNS provider does not properly handle CAA records, failing
  /// requests for CAA records when no CAA records are defined. Renewals will
  /// continue to fail until the DNS provider is changed or a CAA record is
  /// added for the given domain. The last successfully provisioned certificate
  /// may still be serving.
  case failedRetryingCaaChecking
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .ok: return 1
    case .pending: return 2
    case .failedRetryingNotVisible: return 4
    case .failedPermanent: return 6
    case .failedRetryingCaaForbidden: return 7
    case .failedRetryingCaaChecking: return 8
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "MANAGEMENT_STATUS_UNSPECIFIED"
    case .ok: return "OK"
    case .pending: return "PENDING"
    case .failedRetryingNotVisible: return "FAILED_RETRYING_NOT_VISIBLE"
    case .failedPermanent: return "FAILED_PERMANENT"
    case .failedRetryingCaaForbidden: return "FAILED_RETRYING_CAA_FORBIDDEN"
    case .failedRetryingCaaChecking: return "FAILED_RETRYING_CAA_CHECKING"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ManagementStatus/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "MANAGEMENT_STATUS_UNSPECIFIED": self = .unspecified
    case "OK": self = .ok
    case "PENDING": self = .pending
    case "FAILED_RETRYING_NOT_VISIBLE": self = .failedRetryingNotVisible
    case "FAILED_PERMANENT": self = .failedPermanent
    case "FAILED_RETRYING_CAA_FORBIDDEN": self = .failedRetryingCaaForbidden
    case "FAILED_RETRYING_CAA_CHECKING": self = .failedRetryingCaaChecking
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ManagementStatus/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .ok
    case 2: self = .pending
    case 4: self = .failedRetryingNotVisible
    case 6: self = .failedPermanent
    case 7: self = .failedRetryingCaaForbidden
    case 8: self = .failedRetryingCaaChecking
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("MANAGEMENT_STATUS_UNSPECIFIED")
    case .ok: return try container.encode("OK")
    case .pending: return try container.encode("PENDING")
    case .failedRetryingNotVisible: return try container.encode("FAILED_RETRYING_NOT_VISIBLE")
    case .failedPermanent: return try container.encode("FAILED_PERMANENT")
    case .failedRetryingCaaForbidden: return try container.encode("FAILED_RETRYING_CAA_FORBIDDEN")
    case .failedRetryingCaaChecking: return try container.encode("FAILED_RETRYING_CAA_CHECKING")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
