// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Extra network settings.
/// Only applicable in the App Engine flexible environment.
public struct Network: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// List of ports, or port pairs, to forward from the virtual machine to the
  /// application container.
  /// Only applicable in the App Engine flexible environment.
  public var forwardedPorts: [Swift.String] = []

  /// Tag to apply to the instance during creation.
  /// Only applicable in the App Engine flexible environment.
  public var instanceTag: Swift.String = Swift.String()

  /// Google Compute Engine network where the virtual machines are created.
  /// Specify the short name, not the resource path.
  ///
  /// Defaults to `default`.
  public var name: Swift.String = Swift.String()

  /// Google Cloud Platform sub-network where the virtual machines are created.
  /// Specify the short name, not the resource path.
  ///
  /// If a subnetwork name is specified, a network name will also be required
  /// unless it is for the default network.
  ///
  /// * If the network that the instance is being created in is a Legacy network,
  /// then the IP address is allocated from the IPv4Range.
  /// * If the network that the instance is being created in is an auto Subnet
  /// Mode Network, then only network name should be specified (not the
  /// subnetwork_name) and the IP address is created from the IPCidrRange of the
  /// subnetwork that exists in that zone for that network.
  /// * If the network that the instance is being created in is a custom Subnet
  /// Mode Network, then the subnetwork_name must be specified and the
  /// IP address is created from the IPCidrRange of the subnetwork.
  ///
  /// If specified, the subnetwork must exist in the same region as the
  /// App Engine flexible environment application.
  public var subnetworkName: Swift.String = Swift.String()

  /// Enable session affinity.
  /// Only applicable in the App Engine flexible environment.
  public var sessionAffinity: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Network`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Network().with { $0.forwardedPorts = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let forwardedPorts = CodingKeys(stringValue: "forwardedPorts")
    static let instanceTag = CodingKeys(stringValue: "instanceTag")
    static let name = CodingKeys(stringValue: "name")
    static let subnetworkName = CodingKeys(stringValue: "subnetworkName")
    static let sessionAffinity = CodingKeys(stringValue: "sessionAffinity")

    static let _knownKeys: Set<Swift.String> = [
      "forwardedPorts",
      "instanceTag",
      "name",
      "subnetworkName",
      "sessionAffinity",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .forwardedPorts) {
      self.forwardedPorts = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceTag) {
      self.instanceTag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetworkName) {
      self.subnetworkName = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .sessionAffinity) {
      self.sessionAffinity = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.forwardedPorts, forKey: .forwardedPorts)
    try container.encode(self.instanceTag, forKey: .instanceTag)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.subnetworkName, forKey: .subnetworkName)
    try container.encode(self.sessionAffinity, forKey: .sessionAffinity)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Network"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
