// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Target scaling by network usage.
/// Only applicable in the App Engine flexible environment.
public struct NetworkUtilization: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Target bytes sent per second.
  public var targetSentBytesPerSecond: Swift.Int32 = Swift.Int32()

  /// Target packets sent per second.
  public var targetSentPacketsPerSecond: Swift.Int32 = Swift.Int32()

  /// Target bytes received per second.
  public var targetReceivedBytesPerSecond: Swift.Int32 = Swift.Int32()

  /// Target packets received per second.
  public var targetReceivedPacketsPerSecond: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkUtilization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkUtilization().with { $0.targetSentBytesPerSecond = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetSentBytesPerSecond = CodingKeys(stringValue: "targetSentBytesPerSecond")
    static let targetSentPacketsPerSecond = CodingKeys(stringValue: "targetSentPacketsPerSecond")
    static let targetReceivedBytesPerSecond = CodingKeys(
      stringValue: "targetReceivedBytesPerSecond")
    static let targetReceivedPacketsPerSecond = CodingKeys(
      stringValue: "targetReceivedPacketsPerSecond")

    static let _knownKeys: Set<Swift.String> = [
      "targetSentBytesPerSecond",
      "targetSentPacketsPerSecond",
      "targetReceivedBytesPerSecond",
      "targetReceivedPacketsPerSecond",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .targetSentBytesPerSecond)
    {
      self.targetSentBytesPerSecond = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .targetSentPacketsPerSecond)
    {
      self.targetSentPacketsPerSecond = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .targetReceivedBytesPerSecond)
    {
      self.targetReceivedBytesPerSecond = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .targetReceivedPacketsPerSecond)
    {
      self.targetReceivedPacketsPerSecond = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetSentBytesPerSecond, forKey: .targetSentBytesPerSecond)
    try container.encode(self.targetSentPacketsPerSecond, forKey: .targetSentPacketsPerSecond)
    try container.encode(self.targetReceivedBytesPerSecond, forKey: .targetReceivedBytesPerSecond)
    try container.encode(
      self.targetReceivedPacketsPerSecond, forKey: .targetReceivedPacketsPerSecond)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.NetworkUtilization"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
