// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata for the given [google.longrunning.Operation][google.longrunning.Operation].
///
/// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
public struct OperationMetadataV1: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// API method that initiated this operation. Example:
  /// `google.appengine.v1.Versions.CreateVersion`.
  ///
  /// @OutputOnly
  public var method: Swift.String = Swift.String()

  /// Time that this operation was created.
  ///
  /// @OutputOnly
  public var insertTime: GoogleWKT.WKTTimestamp? = nil

  /// Time that this operation completed.
  ///
  /// @OutputOnly
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// User who requested this operation.
  ///
  /// @OutputOnly
  public var user: Swift.String = Swift.String()

  /// Name of the resource that this operation is acting on. Example:
  /// `apps/myapp/services/default`.
  ///
  /// @OutputOnly
  public var target: Swift.String = Swift.String()

  /// Ephemeral message that may change every time the operation is polled.
  /// @OutputOnly
  public var ephemeralMessage: Swift.String = Swift.String()

  /// Durable messages that persist on every operation poll.
  /// @OutputOnly
  public var warning: [Swift.String] = []

  /// Metadata specific to the type of operation in progress.
  /// @OutputOnly
  public var methodMetadata: MethodMetadataOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationMetadataV1`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadataV1().with { $0.method = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let method = CodingKeys(stringValue: "method")
    static let insertTime = CodingKeys(stringValue: "insertTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let user = CodingKeys(stringValue: "user")
    static let target = CodingKeys(stringValue: "target")
    static let ephemeralMessage = CodingKeys(stringValue: "ephemeralMessage")
    static let warning = CodingKeys(stringValue: "warning")
    static let createVersionMetadata = CodingKeys(stringValue: "createVersionMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "method",
      "insertTime",
      "endTime",
      "user",
      "target",
      "ephemeralMessage",
      "warning",
      "createVersionMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .method) {
      self.method = value
    }
    self.insertTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .insertTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .user) {
      self.user = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
      self.target = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ephemeralMessage) {
      self.ephemeralMessage = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .warning) {
      self.warning = value
    }

    var methodMetadata: MethodMetadataOneOf? = nil
    let methodMetadataCheckAndSet = {
      if methodMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'methodMetadata'"))
      }
      methodMetadata = $0
    }
    if let createVersionMetadata = try container.decodeIfPresent(
      CreateVersionMetadataV1?.self, forKey: .createVersionMetadata)
    {
      try methodMetadataCheckAndSet(.createVersionMetadata(createVersionMetadata))
    }
    self.methodMetadata = methodMetadata
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.method, forKey: .method)
    try container.encodeIfPresent(self.insertTime, forKey: .insertTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.user, forKey: .user)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.ephemeralMessage, forKey: .ephemeralMessage)
    try container.encode(self.warning, forKey: .warning)

    if let choice = self.methodMetadata {
      switch choice {
      case .createVersionMetadata(let value):
        try container.encode(value, forKey: .createVersionMetadata)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Metadata specific to the type of operation in progress.
  /// @OutputOnly
  public enum MethodMetadataOneOf: Codable, Equatable, Sendable {
    indirect case createVersionMetadata(CreateVersionMetadataV1?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.OperationMetadataV1"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
