// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Machine resources for a version.
public struct Resources: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Number of CPU cores needed.
  public var cpu: Swift.Double = Swift.Double()

  /// Disk size (GB) needed.
  public var diskGb: Swift.Double = Swift.Double()

  /// Memory (GB) needed.
  public var memoryGb: Swift.Double = Swift.Double()

  /// User specified volumes.
  public var volumes: [Volume] = []

  /// The name of the encryption key that is stored in Google Cloud KMS.
  /// Only should be used by Cloud Composer to encrypt the vm disk
  public var kmsKeyReference: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Resources`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Resources().with { $0.cpu = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cpu = CodingKeys(stringValue: "cpu")
    static let diskGb = CodingKeys(stringValue: "diskGb")
    static let memoryGb = CodingKeys(stringValue: "memoryGb")
    static let volumes = CodingKeys(stringValue: "volumes")
    static let kmsKeyReference = CodingKeys(stringValue: "kmsKeyReference")

    static let _knownKeys: Set<Swift.String> = [
      "cpu",
      "diskGb",
      "memoryGb",
      "volumes",
      "kmsKeyReference",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .cpu) {
      self.cpu = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .diskGb) {
      self.diskGb = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .memoryGb) {
      self.memoryGb = value
    }
    if let value = try container.decodeIfPresent([Volume].self, forKey: .volumes) {
      self.volumes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyReference) {
      self.kmsKeyReference = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cpu, forKey: .cpu)
    try container.encode(self.diskGb, forKey: .diskGb)
    try container.encode(self.memoryGb, forKey: .memoryGb)
    try container.encode(self.volumes, forKey: .volumes)
    try container.encode(self.kmsKeyReference, forKey: .kmsKeyReference)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Resources"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
