// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages services of an application.
///
/// @Snippet(path: "ServicesQuickstart")
public final class ServicesClient: Clients.ServicesProtocol, Sendable {
  let inner: any Clients.ServicesStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `ServicesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServicesStub = try Clients.ServicesTransport(options)
    inner = Clients.ServicesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServicesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all the services in the application.
  ///
  /// @Snippet(path: "Services_ListServices")
  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListServicesResponse {
    try await self.inner.listServices(request: request, options: options)
  }

  /// Gets the current configuration of the specified service.
  ///
  /// @Snippet(path: "Services_GetService")
  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Service {
    try await self.inner.getService(request: request, options: options)
  }

  /// Updates the configuration of the specified service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateService(request: request, options: options)
  }

  /// Updates the configuration of the specified service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  public func updateServicePollingUntilDone(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Service>.State in
      return try op._extractStatus(Service.self)
    }
    let rawOp = try await self.updateService(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified service and all enclosed versions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteService(request: request, options: options)
  }

  /// Deletes the specified service and all enclosed versions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  public func deleteServicePollingUntilDone(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteService(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Services_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Services_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServicesClient`.
  ///
  /// To mock `ServicesClient` change your functions to receive
  /// `some ServicesProtocol` or `any ServicesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServicesProtocol: Sendable {
    /// See `ServicesClient.listServices`.
    func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListServicesResponse

    /// See `ServicesClient.getService`.
    func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.Service

    /// See `ServicesClient.updateService`.
    func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.updateService`.
    func updateServicePollingUntilDone(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Service>

    /// See `ServicesClient.deleteService`.
    func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.deleteService`.
    func deleteServicePollingUntilDone(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ServicesClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.ServicesProtocol {
  public func listServices(request: ListServicesRequest) async throws
    -> GoogleAppEngineV1.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListServicesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listServicesByItems(
    request: ListServicesRequest
  ) -> some AsyncSequence<Service, Swift.Error> & Sendable {
    self.listServicesByItems(request: request, options: .init())
  }

  /// Lists all the services in the application.
  ///
  /// @Snippet(path: "Services_ListServices")
  public func listServicesByItems(
    request: ListServicesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Service, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleAppEngineV1.ListServicesResponse in
      var request = request
      request.pageToken = token
      return try await self.listServices(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getService(request: GetServiceRequest) async throws -> GoogleAppEngineV1.Service {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Service {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateServicePollingUntilDone(request: UpdateServiceRequest) async throws
    -> any GoogleGax.PollableOperation<Service>
  {
    try await self.updateServicePollingUntilDone(request: request, options: .init())
  }

  public func updateServicePollingUntilDone(
    request: UpdateServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Service> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Service>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteService(request: DeleteServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteServicePollingUntilDone(request: DeleteServiceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteServicePollingUntilDone(request: request, options: .init())
  }

  public func deleteServicePollingUntilDone(
    request: DeleteServiceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Services_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
