// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Scheduler settings for standard environment.
public struct StandardSchedulerSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Target CPU utilization ratio to maintain when scaling.
  public var targetCpuUtilization: Swift.Double = Swift.Double()

  /// Target throughput utilization ratio to maintain when scaling
  public var targetThroughputUtilization: Swift.Double = Swift.Double()

  /// Minimum number of instances to run for this version. Set to zero to disable
  /// `min_instances` configuration.
  public var minInstances: Swift.Int32 = Swift.Int32()

  /// Maximum number of instances to run for this version. Set to zero to disable
  /// `max_instances` configuration.
  public var maxInstances: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StandardSchedulerSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StandardSchedulerSettings().with { $0.targetCpuUtilization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let targetCpuUtilization = CodingKeys(stringValue: "targetCpuUtilization")
    static let targetThroughputUtilization = CodingKeys(stringValue: "targetThroughputUtilization")
    static let minInstances = CodingKeys(stringValue: "minInstances")
    static let maxInstances = CodingKeys(stringValue: "maxInstances")

    static let _knownKeys: Set<Swift.String> = [
      "targetCpuUtilization",
      "targetThroughputUtilization",
      "minInstances",
      "maxInstances",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .targetCpuUtilization) {
      self.targetCpuUtilization = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Double.self, forKey: .targetThroughputUtilization)
    {
      self.targetThroughputUtilization = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minInstances) {
      self.minInstances = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxInstances) {
      self.maxInstances = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.targetCpuUtilization, forKey: .targetCpuUtilization)
    try container.encode(self.targetThroughputUtilization, forKey: .targetThroughputUtilization)
    try container.encode(self.minInstances, forKey: .minInstances)
    try container.encode(self.maxInstances, forKey: .maxInstances)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.StandardSchedulerSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
