// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Files served directly to the user for a given URL, such as images, CSS
/// stylesheets, or JavaScript source files. Static file handlers describe which
/// files in the application directory are static files, and which URLs serve
/// them.
public struct StaticFilesHandler: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Path to the static files matched by the URL pattern, from the
  /// application root directory. The path can refer to text matched in groupings
  /// in the URL pattern.
  public var path: Swift.String = Swift.String()

  /// Regular expression that matches the file paths for all files that should be
  /// referenced by this handler.
  public var uploadPathRegex: Swift.String = Swift.String()

  /// HTTP headers to use for all responses from these URLs.
  public var httpHeaders: [Swift.String: Swift.String] = [:]

  /// MIME type used to serve all files served by this handler.
  ///
  /// Defaults to file-specific MIME types, which are derived from each file's
  /// filename extension.
  public var mimeType: Swift.String = Swift.String()

  /// Time a static file served by this handler should be cached
  /// by web proxies and browsers.
  public var expiration: GoogleWKT.WKTDuration? = nil

  /// Whether this handler should match the request if the file
  /// referenced by the handler does not exist.
  public var requireMatchingFile: Swift.Bool = Swift.Bool()

  /// Whether files should also be uploaded as code data. By default, files
  /// declared in static file handlers are uploaded as static
  /// data and are only served to end users; they cannot be read by the
  /// application. If enabled, uploads are charged against both your code and
  /// static data storage resource quotas.
  public var applicationReadable: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StaticFilesHandler`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StaticFilesHandler().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let path = CodingKeys(stringValue: "path")
    static let uploadPathRegex = CodingKeys(stringValue: "uploadPathRegex")
    static let httpHeaders = CodingKeys(stringValue: "httpHeaders")
    static let mimeType = CodingKeys(stringValue: "mimeType")
    static let expiration = CodingKeys(stringValue: "expiration")
    static let requireMatchingFile = CodingKeys(stringValue: "requireMatchingFile")
    static let applicationReadable = CodingKeys(stringValue: "applicationReadable")

    static let _knownKeys: Set<Swift.String> = [
      "path",
      "uploadPathRegex",
      "httpHeaders",
      "mimeType",
      "expiration",
      "requireMatchingFile",
      "applicationReadable",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uploadPathRegex) {
      self.uploadPathRegex = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .httpHeaders)
    {
      self.httpHeaders = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mimeType) {
      self.mimeType = value
    }
    self.expiration = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .expiration)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireMatchingFile) {
      self.requireMatchingFile = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .applicationReadable) {
      self.applicationReadable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.uploadPathRegex, forKey: .uploadPathRegex)
    try container.encode(self.httpHeaders, forKey: .httpHeaders)
    try container.encode(self.mimeType, forKey: .mimeType)
    try container.encodeIfPresent(self.expiration, forKey: .expiration)
    try container.encode(self.requireMatchingFile, forKey: .requireMatchingFile)
    try container.encode(self.applicationReadable, forKey: .applicationReadable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.StaticFilesHandler"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
