// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Version resource is a specific set of source code and configuration files
/// that are deployed into a service.
public struct Version: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Full path to the Version resource in the API.  Example:
  /// `apps/myapp/services/default/versions/v1`.
  ///
  /// @OutputOnly
  public var name: Swift.String = Swift.String()

  /// Relative name of the version within the service.  Example: `v1`.
  /// Version names can contain only lowercase letters, numbers, or hyphens.
  /// Reserved names: "default", "latest", and any name with the prefix "ah-".
  public var id: Swift.String = Swift.String()

  /// Before an application can receive email or XMPP messages, the application
  /// must be configured to enable the service.
  public var inboundServices: [InboundServiceType] = []

  /// Instance class that is used to run this version. Valid values are:
  ///
  /// * AutomaticScaling: `F1`, `F2`, `F4`, `F4_1G`
  /// * ManualScaling or BasicScaling: `B1`, `B2`, `B4`, `B8`, `B4_1G`
  ///
  /// Defaults to `F1` for AutomaticScaling and `B1` for ManualScaling or
  /// BasicScaling.
  public var instanceClass: Swift.String = Swift.String()

  /// Extra network settings.
  /// Only applicable in the App Engine flexible environment.
  public var network: Network? = nil

  /// The Google Compute Engine zones that are supported by this version in the
  /// App Engine flexible environment. Deprecated.
  public var zones: [Swift.String] = []

  /// Machine resources for this version.
  /// Only applicable in the App Engine flexible environment.
  public var resources: Resources? = nil

  /// Desired runtime. Example: `python27`.
  public var runtime: Swift.String = Swift.String()

  /// The channel of the runtime to use. Only available for some
  /// runtimes. Defaults to the `default` channel.
  public var runtimeChannel: Swift.String = Swift.String()

  /// Whether multiple requests can be dispatched to this version at once.
  public var threadsafe: Swift.Bool = Swift.Bool()

  /// Whether to deploy this version in a container on a virtual machine.
  public var vm: Swift.Bool = Swift.Bool()

  /// Allows App Engine second generation runtimes to access the legacy bundled
  /// services.
  public var appEngineApis: Swift.Bool = Swift.Bool()

  /// Metadata settings that are supplied to this version to enable
  /// beta runtime features.
  public var betaSettings: [Swift.String: Swift.String] = [:]

  /// App Engine execution environment for this version.
  ///
  /// Defaults to `standard`.
  public var env: Swift.String = Swift.String()

  /// Current serving status of this version. Only the versions with a
  /// `SERVING` status create instances and can be billed.
  ///
  /// `SERVING_STATUS_UNSPECIFIED` is an invalid value. Defaults to `SERVING`.
  public var servingStatus: ServingStatus = ServingStatus()

  /// Email address of the user who created this version.
  ///
  /// @OutputOnly
  public var createdBy: Swift.String = Swift.String()

  /// Time that this version was created.
  ///
  /// @OutputOnly
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Total size in bytes of all the files that are included in this version
  /// and currently hosted on the App Engine disk.
  ///
  /// @OutputOnly
  public var diskUsageBytes: Swift.Int64 = Swift.Int64()

  /// The version of the API in the given runtime environment. Please see the
  /// app.yaml reference for valid values at
  /// https://cloud.google.com/appengine/docs/standard/<language>/config/appref
  public var runtimeApiVersion: Swift.String = Swift.String()

  /// The path or name of the app's main executable.
  public var runtimeMainExecutablePath: Swift.String = Swift.String()

  /// The identity that the deployed version will run as.
  /// Admin API will use the App Engine Appspot service account as default if
  /// this field is neither provided in app.yaml file nor through CLI flag.
  public var serviceAccount: Swift.String = Swift.String()

  /// An ordered list of URL-matching patterns that should be applied to incoming
  /// requests. The first matching URL handles the request and other request
  /// handlers are not attempted.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var handlers: [UrlMap] = []

  /// Custom static error pages. Limited to 10KB per page.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var errorHandlers: [ErrorHandler] = []

  /// Configuration for third-party Python runtime libraries that are required
  /// by the application.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var libraries: [Library] = []

  /// Serving configuration for
  /// [Google Cloud Endpoints](https://cloud.google.com/appengine/docs/python/endpoints/).
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var apiConfig: ApiConfigHandler? = nil

  /// Environment variables available to the application.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var envVariables: [Swift.String: Swift.String] = [:]

  /// Environment variables available to the build environment.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var buildEnvVariables: [Swift.String: Swift.String] = [:]

  /// Duration that static files should be cached by web proxies and browsers.
  /// Only applicable if the corresponding
  /// [StaticFilesHandler](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#StaticFilesHandler)
  /// does not specify its own expiration time.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var defaultExpiration: GoogleWKT.WKTDuration? = nil

  /// Configures health checking for instances. Unhealthy instances are
  /// stopped and replaced with new instances.
  /// Only applicable in the App Engine flexible environment.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var healthCheck: HealthCheck? = nil

  /// Configures readiness health checking for instances.
  /// Unhealthy instances are not put into the backend traffic rotation.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var readinessCheck: ReadinessCheck? = nil

  /// Configures liveness health checking for instances.
  /// Unhealthy instances are stopped and replaced with new instances
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var livenessCheck: LivenessCheck? = nil

  /// Files that match this pattern will not be built into this version.
  /// Only applicable for Go runtimes.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var nobuildFilesRegex: Swift.String = Swift.String()

  /// Code and application artifacts that make up this version.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var deployment: Deployment? = nil

  /// Serving URL for this version. Example:
  /// "https://myversion-dot-myservice-dot-myapp.appspot.com"
  ///
  /// @OutputOnly
  public var versionUrl: Swift.String = Swift.String()

  /// Cloud Endpoints configuration.
  ///
  /// If endpoints_api_service is set, the Cloud Endpoints Extensible Service
  /// Proxy will be provided to serve the API implemented by the app.
  public var endpointsApiService: EndpointsApiService? = nil

  /// The entrypoint for the application.
  public var entrypoint: Entrypoint? = nil

  /// Enables VPC connectivity for standard apps.
  public var vpcAccessConnector: VpcAccessConnector? = nil

  /// Controls how instances are created, scaled, and reaped.
  ///
  /// Defaults to `AutomaticScaling`.
  public var scaling: OneOf_Scaling? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Version`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Version().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let id = CodingKeys(stringValue: "id")
    static let automaticScaling = CodingKeys(stringValue: "automaticScaling")
    static let basicScaling = CodingKeys(stringValue: "basicScaling")
    static let manualScaling = CodingKeys(stringValue: "manualScaling")
    static let inboundServices = CodingKeys(stringValue: "inboundServices")
    static let instanceClass = CodingKeys(stringValue: "instanceClass")
    static let network = CodingKeys(stringValue: "network")
    static let zones = CodingKeys(stringValue: "zones")
    static let resources = CodingKeys(stringValue: "resources")
    static let runtime = CodingKeys(stringValue: "runtime")
    static let runtimeChannel = CodingKeys(stringValue: "runtimeChannel")
    static let threadsafe = CodingKeys(stringValue: "threadsafe")
    static let vm = CodingKeys(stringValue: "vm")
    static let appEngineApis = CodingKeys(stringValue: "appEngineApis")
    static let betaSettings = CodingKeys(stringValue: "betaSettings")
    static let env = CodingKeys(stringValue: "env")
    static let servingStatus = CodingKeys(stringValue: "servingStatus")
    static let createdBy = CodingKeys(stringValue: "createdBy")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let diskUsageBytes = CodingKeys(stringValue: "diskUsageBytes")
    static let runtimeApiVersion = CodingKeys(stringValue: "runtimeApiVersion")
    static let runtimeMainExecutablePath = CodingKeys(stringValue: "runtimeMainExecutablePath")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let handlers = CodingKeys(stringValue: "handlers")
    static let errorHandlers = CodingKeys(stringValue: "errorHandlers")
    static let libraries = CodingKeys(stringValue: "libraries")
    static let apiConfig = CodingKeys(stringValue: "apiConfig")
    static let envVariables = CodingKeys(stringValue: "envVariables")
    static let buildEnvVariables = CodingKeys(stringValue: "buildEnvVariables")
    static let defaultExpiration = CodingKeys(stringValue: "defaultExpiration")
    static let healthCheck = CodingKeys(stringValue: "healthCheck")
    static let readinessCheck = CodingKeys(stringValue: "readinessCheck")
    static let livenessCheck = CodingKeys(stringValue: "livenessCheck")
    static let nobuildFilesRegex = CodingKeys(stringValue: "nobuildFilesRegex")
    static let deployment = CodingKeys(stringValue: "deployment")
    static let versionUrl = CodingKeys(stringValue: "versionUrl")
    static let endpointsApiService = CodingKeys(stringValue: "endpointsApiService")
    static let entrypoint = CodingKeys(stringValue: "entrypoint")
    static let vpcAccessConnector = CodingKeys(stringValue: "vpcAccessConnector")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "id",
      "automaticScaling",
      "basicScaling",
      "manualScaling",
      "inboundServices",
      "instanceClass",
      "network",
      "zones",
      "resources",
      "runtime",
      "runtimeChannel",
      "threadsafe",
      "vm",
      "appEngineApis",
      "betaSettings",
      "env",
      "servingStatus",
      "createdBy",
      "createTime",
      "diskUsageBytes",
      "runtimeApiVersion",
      "runtimeMainExecutablePath",
      "serviceAccount",
      "handlers",
      "errorHandlers",
      "libraries",
      "apiConfig",
      "envVariables",
      "buildEnvVariables",
      "defaultExpiration",
      "healthCheck",
      "readinessCheck",
      "livenessCheck",
      "nobuildFilesRegex",
      "deployment",
      "versionUrl",
      "endpointsApiService",
      "entrypoint",
      "vpcAccessConnector",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(
      [InboundServiceType].self, forKey: .inboundServices)
    {
      self.inboundServices = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceClass) {
      self.instanceClass = value
    }
    self.network = try container.decodeIfPresent(Network.self, forKey: .network)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .zones) {
      self.zones = value
    }
    self.resources = try container.decodeIfPresent(Resources.self, forKey: .resources)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .runtime) {
      self.runtime = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .runtimeChannel) {
      self.runtimeChannel = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .threadsafe) {
      self.threadsafe = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .vm) {
      self.vm = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .appEngineApis) {
      self.appEngineApis = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .betaSettings)
    {
      self.betaSettings = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .env) {
      self.env = value
    }
    if let value = try container.decodeIfPresent(ServingStatus.self, forKey: .servingStatus) {
      self.servingStatus = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .createdBy) {
      self.createdBy = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .diskUsageBytes) {
      self.diskUsageBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .runtimeApiVersion) {
      self.runtimeApiVersion = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .runtimeMainExecutablePath)
    {
      self.runtimeMainExecutablePath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent([UrlMap].self, forKey: .handlers) {
      self.handlers = value
    }
    if let value = try container.decodeIfPresent([ErrorHandler].self, forKey: .errorHandlers) {
      self.errorHandlers = value
    }
    if let value = try container.decodeIfPresent([Library].self, forKey: .libraries) {
      self.libraries = value
    }
    self.apiConfig = try container.decodeIfPresent(ApiConfigHandler.self, forKey: .apiConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .envVariables)
    {
      self.envVariables = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .buildEnvVariables)
    {
      self.buildEnvVariables = value
    }
    self.defaultExpiration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .defaultExpiration)
    self.healthCheck = try container.decodeIfPresent(HealthCheck.self, forKey: .healthCheck)
    self.readinessCheck = try container.decodeIfPresent(
      ReadinessCheck.self, forKey: .readinessCheck)
    self.livenessCheck = try container.decodeIfPresent(LivenessCheck.self, forKey: .livenessCheck)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nobuildFilesRegex) {
      self.nobuildFilesRegex = value
    }
    self.deployment = try container.decodeIfPresent(Deployment.self, forKey: .deployment)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionUrl) {
      self.versionUrl = value
    }
    self.endpointsApiService = try container.decodeIfPresent(
      EndpointsApiService.self, forKey: .endpointsApiService)
    self.entrypoint = try container.decodeIfPresent(Entrypoint.self, forKey: .entrypoint)
    self.vpcAccessConnector = try container.decodeIfPresent(
      VpcAccessConnector.self, forKey: .vpcAccessConnector)

    var scaling: OneOf_Scaling? = nil
    let scalingCheckAndSet = {
      if scaling != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'scaling'"))
      }
      scaling = $0
    }
    if let automaticScaling = try container.decodeIfPresent(
      AutomaticScaling?.self, forKey: .automaticScaling)
    {
      try scalingCheckAndSet(.automaticScaling(automaticScaling))
    }
    if let basicScaling = try container.decodeIfPresent(BasicScaling?.self, forKey: .basicScaling) {
      try scalingCheckAndSet(.basicScaling(basicScaling))
    }
    if let manualScaling = try container.decodeIfPresent(
      ManualScaling?.self, forKey: .manualScaling)
    {
      try scalingCheckAndSet(.manualScaling(manualScaling))
    }
    self.scaling = scaling
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.inboundServices, forKey: .inboundServices)
    try container.encode(self.instanceClass, forKey: .instanceClass)
    try container.encodeIfPresent(self.network, forKey: .network)
    try container.encode(self.zones, forKey: .zones)
    try container.encodeIfPresent(self.resources, forKey: .resources)
    try container.encode(self.runtime, forKey: .runtime)
    try container.encode(self.runtimeChannel, forKey: .runtimeChannel)
    try container.encode(self.threadsafe, forKey: .threadsafe)
    try container.encode(self.vm, forKey: .vm)
    try container.encode(self.appEngineApis, forKey: .appEngineApis)
    try container.encode(self.betaSettings, forKey: .betaSettings)
    try container.encode(self.env, forKey: .env)
    try container.encode(self.servingStatus, forKey: .servingStatus)
    try container.encode(self.createdBy, forKey: .createdBy)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.diskUsageBytes, forKey: .diskUsageBytes)
    try container.encode(self.runtimeApiVersion, forKey: .runtimeApiVersion)
    try container.encode(self.runtimeMainExecutablePath, forKey: .runtimeMainExecutablePath)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.handlers, forKey: .handlers)
    try container.encode(self.errorHandlers, forKey: .errorHandlers)
    try container.encode(self.libraries, forKey: .libraries)
    try container.encodeIfPresent(self.apiConfig, forKey: .apiConfig)
    try container.encode(self.envVariables, forKey: .envVariables)
    try container.encode(self.buildEnvVariables, forKey: .buildEnvVariables)
    try container.encodeIfPresent(self.defaultExpiration, forKey: .defaultExpiration)
    try container.encodeIfPresent(self.healthCheck, forKey: .healthCheck)
    try container.encodeIfPresent(self.readinessCheck, forKey: .readinessCheck)
    try container.encodeIfPresent(self.livenessCheck, forKey: .livenessCheck)
    try container.encode(self.nobuildFilesRegex, forKey: .nobuildFilesRegex)
    try container.encodeIfPresent(self.deployment, forKey: .deployment)
    try container.encode(self.versionUrl, forKey: .versionUrl)
    try container.encodeIfPresent(self.endpointsApiService, forKey: .endpointsApiService)
    try container.encodeIfPresent(self.entrypoint, forKey: .entrypoint)
    try container.encodeIfPresent(self.vpcAccessConnector, forKey: .vpcAccessConnector)

    if let choice = self.scaling {
      switch choice {
      case .automaticScaling(let value):
        try container.encode(value, forKey: .automaticScaling)
      case .basicScaling(let value):
        try container.encode(value, forKey: .basicScaling)
      case .manualScaling(let value):
        try container.encode(value, forKey: .manualScaling)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Controls how instances are created, scaled, and reaped.
  ///
  /// Defaults to `AutomaticScaling`.
  public enum OneOf_Scaling: Codable, Equatable, Sendable {
    /// Automatic scaling is based on request rate, response latencies, and other
    /// application metrics. Instances are dynamically created and destroyed as
    /// needed in order to handle traffic.
    indirect case automaticScaling(AutomaticScaling?)
    /// A service with basic scaling will create an instance when the application
    /// receives a request. The instance will be turned down when the app becomes
    /// idle. Basic scaling is ideal for work that is intermittent or driven by
    /// user activity.
    indirect case basicScaling(BasicScaling?)
    /// A service with manual scaling runs continuously, allowing you to perform
    /// complex initialization and rely on the state of its memory over time.
    /// Manually scaled versions are sometimes referred to as "backends".
    indirect case manualScaling(ManualScaling?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Version"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
